# STAGE 1: Build the application
FROM maven:3.9-eclipse-temurin-25-alpine AS builder
WORKDIR /build

# 1. Optimization: Copy Java and Node dependency manifests first
# This allows Docker to cache dependencies and speed up future builds
COPY pom.xml .
COPY package.json package-lock.json* ./

# Download Java dependencies
# Note: npm install will be handled by the frontend-maven-plugin during the package phase
RUN mvn dependency:go-offline -B

# 2. Copy source and build the JAR
COPY src ./src

# This runs npm install, Terser (JS minify), and PostCSS (CSS bundling)
# as defined in your pom.xml executions.
RUN mvn clean package -DskipTests

# STAGE 2: Create the runtime image
FROM azul/zulu-openjdk-alpine:25-jre-headless
WORKDIR /app

# Best Practice: Run as a non-root user for security
RUN addgroup -S spring && adduser -S spring -G spring
USER spring

# Copy the JAR from the builder stage
# We use the wildcard to catch the versioned JAR generated by Maven
COPY --from=builder /build/target/*.jar app.jar

# Optimized for container resources
# MaxRAMPercentage ensures the JVM respects Docker memory limits
ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]