package com.example.mtg_deckbuilder.repository.tables

import org.jetbrains.exposed.v1.core.dao.id.IntIdTable
import org.jetbrains.exposed.v1.core.dao.id.java.UUIDTable
import kotlin.uuid.ExperimentalUuidApi

object Tasks : UUIDTable("tasks") {
    @OptIn(ExperimentalUuidApi::class)
    val title = uuid("id")
    val description = varchar("description", 128)
    val isCompleted = bool("completed").default(false)
    val oracleId          = text("oracle_id").nullable()
    val multiverseIds     = array<Int>("multiverse_ids").nullable()
    val mtgoId            = integer("mtgo_id").nullable()
    val mtgoFoilId        = integer("mtgo_foil_id").nullable()
    val tcgplayerId       = integer("tcgplayer_id").nullable()
    val tcgplayerEtchedId = integer("tcgplayer_etched_id").nullable()
    val cardmarketId      = integer("cardmarket_id").nullable()
    val lang              = text("lang").nullable()
    val releasedAt        = text("released_at").nullable()
    val uri               = text("uri").nullable()
    val scryfallUri       = text("scryfall_uri").nullable()
    val layout            = text("layout").nullable()
    val highresImage      = bool("highres_image").nullable()
    val imageStatus       = text("image_status").nullable()
    val name              = text("name")
    val manaCost          = text("mana_cost").nullable()
    val cmc               = decimal("cmc", 10, 2).nullable()
    val typeLine          = text("type_line").nullable()
    val oracleText        = text("oracle_text").nullable()
    val power             = text("power").nullable()
    val toughness         = text("toughness").nullable()
    val loyalty           = text("loyalty").nullable()
    val defense           = text("defense").nullable()
    val colors            = array<String>("colors").nullable()
    val colorIdentity     = array<String>("color_identity").nullable()
    val colorIndicator    = array<String>("color_indicator").nullable()
    val keywords          = array<String>("keywords").nullable()
    val producedMana      = array<String>("produced_mana").nullable()
    val reserved          = bool("reserved").nullable()
    val gameChanger       = bool("game_changer").nullable()
    /**
    val imageUris         = jsonb("image_uris").nullable()
    val legalities        = jsonb("legalities").nullable()
    val allParts          = jsonb("all_parts").nullable()
    val cardFaces         = jsonb("card_faces").nullable()
    val prices            = jsonb("prices").nullable()
    val purchaseUris      = jsonb("purchase_uris").nullable()
    val relatedUris       = jsonb("related_uris").nullable()
    val preview           = jsonb("preview").nullable()
    val artist            = text("artist").nullable()
    */
    val artistIds         = array<String>("artist_ids").nullable()
    val illustrationId    = text("illustration_id").nullable()
    val flavorText        = text("flavor_text").nullable()
    val flavorName        = text("flavor_name").nullable()
    val watermark         = text("watermark").nullable()
    val borderColor       = text("border_color").nullable()
    val frame             = text("frame").nullable()
    val frameEffects      = array<String>("frame_effects").nullable()
    val securityStamp     = text("security_stamp").nullable()
    val fullArt           = bool("full_art").nullable()
    val textless          = bool("textless").nullable()
    val oversized         = bool("oversized").nullable()
    val booster           = bool("booster").nullable()
    val digital           = bool("digital").nullable()
    val foil              = bool("foil").nullable()
    val nonfoil           = bool("nonfoil").nullable()
    val finishes          = array<String>("finishes").nullable()
    val games             = array<String>("games").nullable()
    val promo             = bool("promo").nullable()
    val promoTypes        = array<String>("promo_types").nullable()
    val reprint           = bool("reprint").nullable()
    val variation         = bool("variation").nullable()
    val variationOf       = text("variation_of").nullable()
    val storySpotlight    = bool("story_spotlight").nullable()
    val collectorNumber   = text("collector_number").nullable()
    val rarity            = text("rarity").nullable()
    val cardBackId        = text("card_back_id").nullable()
    val setId             = text("set_id").nullable()
    val setCode           = text("set_code").nullable()
    val setName           = text("set_name").nullable()
    val setType           = text("set_type").nullable()
    val setUri            = text("set_uri").nullable()
    val setSearchUri      = text("set_search_uri").nullable()
    val scryfallSetUri    = text("scryfall_set_uri").nullable()
    val rulingsUri        = text("rulings_uri").nullable()
    val printsSearchUri   = text("prints_search_uri").nullable()
    val edhrecRank        = integer("edhrec_rank").nullable()
    val pennyRank         = integer("penny_rank").nullable()
    val handModifier      = text("hand_modifier").nullable()
    val lifeModifier      = text("life_modifier").nullable()

}