spring.application.name=mtg_deckbuilder


# Database URL, User, and Password
# Credentails
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://dpg-d6pp3stm5p6s73fof4j0-a.oregon-postgres.render.com/mtg_deckbuilding}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}
vWaKHbKPfIB8vPDJEIkNwDjR3AhMFlmB
mtg_deckbuilding_user

postgresql://mtg_deckbuilding_user:vWaKHbKPfIB8vPDJEIkNwDjR3AhMFlmB@dpg-d6pp3stm5p6s73fof4j0-a/mtg_deckbuilding
postgresql://mtg_deckbuilding_user:vWaKHbKPfIB8vPDJEIkNwDjR3AhMFlmB@dpg-d6pp3stm5p6s73fof4j0-a/mtg_deckbuilding
# Optional: HikariCP connection pool settings (Highly recommended for performance)
spring.datasource.hikari.maximum-pool-size=10
# Enable compression
server.compression.enabled=true
# Only compress these types to avoid wasting CPU on images
server.compression.mime-types=text/html,text/css,text/javascript,application/javascript
# Only compress files larger than 2KB (compression is pointless on tiny files)
server.compression.min-response-size=2048