spring.application.name=mtg_deckbuilder

# Database URL, User, and Password
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=ddt
spring.datasource.password=Xmac2020@

# Optional: HikariCP connection pool settings (Highly recommended for performance)
spring.datasource.hikari.maximum-pool-size=10