spring.application.name=mtg_deckbuilder


# Database URL, User, and Password
# Credentails
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=ddt
spring.datasource.password=Xmac2020@

server.tomcat.max-part-count=200

# Optional: HikariCP connection pool settings (Highly recommended for performance)
spring.datasource.hikari.maximum-pool-size=10
# Enable compression
server.compression.enabled=true
# Only compress these types to avoid wasting CPU on images
server.compression.mime-types=text/html,text/css,text/javascript,application/javascript
# Only compress files larger than 2KB (compression is pointless on tiny files)
server.compression.min-response-size=2048

scanner.host=localhost
scanner.port=50051
